site_name: XYZ万事屋
site_description: 个人博客
site_url: https://fantasyzeroxyz.github.io  # 必须设置，用于RSS和社交卡片
repo_url: https://github.com/FantasyzeroXYZ/FantasyzeroXYZ.github.io
repo_name: FantasyzeroXYZ/FantasyzeroXYZ.github.io

theme:
  name: material
  locale: zh_Hans_CN  # 简体中文
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.sections

plugins:
  - search:
  - blog:
      blog_toc: true
      archive_date_format: MMMM yyyy
      categories_allowed:
        - Holidays
        - News
      pagination_per_page: 5
      post_slugify: !!python/object/apply:ext.slugs.slugify
        kwds:
          short: true
  - meta
  - tags
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated

extra:
  social:
    - icon: fontawesome/brands/mastodon
      name: squidfunk on Mastodon
      link: https://fosstodon.org/@squidfunk

hooks:
  - hooks/socialmedia.py

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Tags: tags.md
  - Blog:
      - Blog Home: blog/index.md
      - Blog Tags: blog/tags.md
      # 如果不需要作者页面，请移除下面这行
      # - Authors: blog/author/index.md